name: therapy_notes_app
description: A Flutter app for therapists to manage clients and generate case notes.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^10.2.0
  intl: ^0.20.2

flutter:
  uses-material-design: true